const { heroui } = require('@heroui/react');

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,ts,jsx,tsx}', './node_modules/@heroui/theme/dist/**/*.{js,ts,jsx,tsx}'],
  theme: {
    borderRadius: {
      DEFAULT: '4px',
      sm: '0.5rem',
      md: '0.7rem',
      lg: '0.9rem',
    },
    extend: {
      fontSize: {
        tiny: '0.65rem',
        small: '0.75rem',
        medium: '1rem',
        large: '1.125rem',
      },
      colors: {
        default: 'var(--tg-theme-secondary-bg-color)',
        background: 'var(--tg-theme-bg-color)',
        foreground: 'var(--tg-theme-text-color)',
        primary: 'var(--tg-theme-button-color)',
        'primary-text': 'var(--tg-theme-button-text-color)',
        secondary: 'var(--tg-theme-secondary-bg-color)',
        header: 'var(--tg-theme-header-bg-color)',
        accent: 'var(--tg-theme-accent-text-color)',
        link: 'var(--tg-theme-link-color)',
        hint: 'var(--tg-theme-hint-color)',
        subtitle: 'var(--tg-theme-subtitle-text-color)',
        destructive: 'var(--tg-theme-destructive-text-color)',
        section: {
          bg: 'var(--tg-theme-section-bg-color)',
          header: 'var(--tg-theme-section-header-text-color)',
          separator: 'var(--tg-theme-section-separator-color)',
        },
        bottomBar: 'var(--tg-theme-bottom-bar-bg-color)',
      },
      textColor: {
        DEFAULT: 'var(--tg-theme-text-color)',
        primary: 'var(--tg-theme-button-text-color)',
        hint: 'var(--tg-theme-hint-color)',
        subtitle: 'var(--tg-theme-subtitle-text-color)',
        danger: 'var(--tg-theme-destructive-text-color)',
      },
      backgroundColor: {
        DEFAULT: 'var(--tg-theme-bg-color)',
        primary: 'var(--tg-theme-button-color)',
        secondary: 'var(--tg-theme-secondary-bg-color)',
        header: 'var(--tg-theme-header-bg-color)',
        section: 'var(--tg-theme-section-bg-color)',
        bottomBar: 'var(--tg-theme-bottom-bar-bg-color)',
      },
      borderColor: {
        section: 'var(--tg-theme-section-separator-color)',
      },
    },
    container: {
      center: true,
      padding: {
        DEFAULT: '0',
        sm: '1rem',
        lg: '2rem',
        xl: '3rem',
      },
      screens: {
        sm: '320px',
        md: '375px',
        lg: '425px',
        xl: '768px',
      },
    },
  },
  plugins: [
    heroui({
      layout: {
        disabledOpacity: '0.5',
        fontSize: {
          tiny: '0.75rem',
          small: '0.875rem',
          medium: '1rem',
          large: '1.125rem',
        },
        lineHeight: {
          tiny: '1rem',
          small: '1.25rem',
          medium: '1.5rem',
          large: '1.625rem',
        },
        radius: {
          small: '0.2rem',
          medium: '0.4rem',
          large: '0.75rem',
        },
        dividerWeight: '0.75px',
      },
      prefix: 'tg',
      // addCommonColors: true,
      themes: {
        telegram: {
          extend: 'var(--tg-color-scheme)',
          colors: {
            background: 'var(--tg-theme-bg-color)',
            foreground: 'var(--tg-theme-text-color)',
            divider: 'var(--tg-theme-section-separator-color)',
            overlay: 'var(--tg-theme-secondary-bg-color)',
            focus: 'var(--tg-theme-link-color)',
            content1: {
              DEFAULT: 'var(--tg-theme-bg-color)',
              foreground: 'var(--tg-theme-text-color)',
            },
            content2: {
              DEFAULT: 'var(--tg-theme-secondary-bg-color)',
              foreground: 'var(--tg-theme-text-color)',
            },
            content3: {
              DEFAULT: 'var(--tg-theme-section-bg-color)',
              foreground: 'var(--tg-theme-text-color)',
            },
            content4: {
              DEFAULT: 'var(--tg-theme-section-separator-color)',
              foreground: 'var(--tg-theme-text-color)',
            },
            default: {
              50: 'var(--tg-theme-hint-color)',
              100: 'var(--tg-theme-hint-color)',
              200: 'var(--tg-theme-hint-color)',
              300: 'var(--tg-theme-hint-color)',
              400: 'var(--tg-theme-hint-color)',
              500: 'var(--tg-theme-hint-color)',
              600: 'var(--tg-theme-hint-color)',
              700: 'var(--tg-theme-hint-color)',
              800: 'var(--tg-theme-hint-color)',
              900: 'var(--tg-theme-hint-color)',
              foreground: 'var(--tg-theme-text-color)',
              DEFAULT: 'var(--tg-theme-hint-color)',
            },
            primary: {
              50: 'var(--tg-theme-button-color)',
              100: 'var(--tg-theme-button-color)',
              200: 'var(--tg-theme-button-color)',
              300: 'var(--tg-theme-button-color)',
              400: 'var(--tg-theme-button-color)',
              500: 'var(--tg-theme-button-color)',
              600: 'var(--tg-theme-button-color)',
              700: 'var(--tg-theme-button-color)',
              800: 'var(--tg-theme-button-color)',
              900: 'var(--tg-theme-button-color)',
              foreground: 'var(--tg-theme-button-text-color)',
              DEFAULT: 'var(--tg-theme-button-color)',
            },
            secondary: {
              50: 'var(--tg-theme-section-header-text-color)',
              100: 'var(--tg-theme-section-header-text-color)',
              200: 'var(--tg-theme-section-header-text-color)',
              300: 'var(--tg-theme-section-header-text-color)',
              400: 'var(--tg-theme-section-header-text-color)',
              500: 'var(--tg-theme-section-header-text-color)',
              600: 'var(--tg-theme-section-header-text-color)',
              700: 'var(--tg-theme-section-header-text-color)',
              800: 'var(--tg-theme-section-header-text-color)',
              900: 'var(--tg-theme-section-header-text-color)',
              foreground: 'var(--tg-theme-button-text-color)',
              DEFAULT: 'var(--tg-theme-section-header-text-color)',
            },
            success: {
              50: 'var(--tg-theme-link-color)',
              100: 'var(--tg-theme-link-color)',
              200: 'var(--tg-theme-link-color)',
              300: 'var(--tg-theme-link-color)',
              400: 'var(--tg-theme-link-color)',
              500: 'var(--tg-theme-link-color)',
              600: 'var(--tg-theme-link-color)',
              700: 'var(--tg-theme-link-color)',
              800: 'var(--tg-theme-link-color)',
              900: 'var(--tg-theme-link-color)',
              foreground: 'var(--tg-theme-button-text-color)',
              DEFAULT: 'var(--tg-theme-link-color)',
            },
            warning: {
              50: 'var(--tg-theme-destructive-text-color)',
              100: 'var(--tg-theme-destructive-text-color)',
              200: 'var(--tg-theme-destructive-text-color)',
              300: 'var(--tg-theme-destructive-text-color)',
              400: 'var(--tg-theme-destructive-text-color)',
              500: 'var(--tg-theme-destructive-text-color)',
              600: 'var(--tg-theme-destructive-text-color)',
              700: 'var(--tg-theme-destructive-text-color)',
              800: 'var(--tg-theme-destructive-text-color)',
              900: 'var(--tg-theme-destructive-text-color)',
              foreground: 'var(--tg-theme-button-text-color)',
              DEFAULT: 'var(--tg-theme-destructive-text-color)',
            },
            danger: {
              50: 'var(--tg-theme-destructive-text-color)',
              100: 'var(--tg-theme-destructive-text-color)',
              200: 'var(--tg-theme-destructive-text-color)',
              300: 'var(--tg-theme-destructive-text-color)',
              400: 'var(--tg-theme-destructive-text-color)',
              500: 'var(--tg-theme-destructive-text-color)',
              600: 'var(--tg-theme-destructive-text-color)',
              700: 'var(--tg-theme-destructive-text-color)',
              800: 'var(--tg-theme-destructive-text-color)',
              900: 'var(--tg-theme-destructive-text-color)',
              foreground: 'var(--tg-theme-button-text-color)',
              DEFAULT: 'var(--tg-theme-destructive-text-color)',
            },
          },
          layout: {
            fontSize: {
              tiny: '0.3rem',
              small: '0.5rem',
              medium: '0.7rem',
              large: '0.9rem',
            },
            lineHeight: {
              tiny: '0.3rem',
              small: '0.5rem',
              medium: '0.7rem',
              large: '0.9rem',
            },
            radius: {
              small: '0.5rem',
              medium: '0.7rem',
              large: '0.9rem',
            },
            disabledOpacity: 0.5,
            hoverOpacity: 0.7,
            dividerWeight: '1px',
            borderWidth: {
              small: '1px',
              medium: '2px',
              large: '3px',
            },
            boxShadow: {
              small: '0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1)',
              medium: '0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1)',
              large: '0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1)',
            },
          },
        },
      },
      defaultTheme: 'telegram',
    }),
  ],
};
