name: Build & Publish Web Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      # 1. Checkout source
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Extract metadata (tags & labels)
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/telemora/telemora-web
          tags: |
            type=raw,value=latest
            type=sha,prefix=,format=short

      # 4. Build & Push image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/telemora/telemora-web:buildcache
          cache-to: type=registry,ref=ghcr.io/telemora/telemora-web:buildcache,mode=max

      # 5. Trigger deploy repo workflow
      - name: Trigger deployment
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
          repository: telemora/telemora-deploy
          event-type: trigger-deploy
          client-payload: |
            {
              "service": "web",
              "image": "ghcr.io/telemora/telemora-web:${{ github.sha }}",
              "branch": "main"
            }
