name: Build & Push (web) + Dispatch Deploy
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/telemora/telemora-web

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/telemora/telemora-web:latest
            ghcr.io/telemora/telemora-web:sha-${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}

      - name: Generate GitHub App token
        id: app_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Dispatch to deploy repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ steps.app_token.outputs.token }}
          repository: telemora/telemora-deploy
          event-type: trigger-deploy
          client-payload: >-
            {
              "service": "next-js",
              "image": "ghcr.io/telemora/telemora-web",
              "tag": "sha-${{ github.sha }}"
            }
